name: Build and Push Images

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: az acr login --name alexacr1234

      # Build Spring Boot jar
      - name: Build backend
        working-directory: backend
        run: mvn clean package -DskipTests

      # Build Docker images
      - name: Build backend image
        run: docker build -t alexacr1234.azurecr.io/backend-app-githubaction:latest ./backend

      - name: Build frontend image
        run: docker build -t alexacr1234.azurecr.io/frontend-app-githubaction:latest ./frontend

      # Push images
      - name: Push backend image
        run: docker push alexacr1234.azurecr.io/backend-app-githubaction:latest

      - name: Push frontend image
        run: docker push alexacr1234.azurecr.io/frontend-app-githubaction:latest